name: Release
on:
  push:
    branches:
      - master
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: PR Tests
        run: npm ci
        run: npm run test:prod
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
