name: Release
on:
  push:
    branches:
      - master
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Test
      - run: npm ci
      - run: npm run test:prod
      - name: Build
        run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - run: npm ci
      - name: Build Docs
      - run: npm run docs:deploy
      - uses: peaceiris/actions-gh-pages@v3.6.1
        if: contains(github.ref, 'master')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

